language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    packages:
    - shellcheck

script:
 - shellcheck pre-build-buildpack

matrix:
  fast_finish: true