#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

apt_get_install_main() {
  local APP="$1"
  local IMG="dokku/$APP"
  local LST="/home/dokku/${APP}/apt-packages"
  local PKG

  if [ -f "$LST" ] ; then
    PKG=$(xargs < "$LST")
    echo "-----> installing packages from ${LST}..."

    CMD=$(cat <<-EOF
      export DEBIAN_FRONTEND=noninteractive
      if [ -n "$PKG" ] ; then
          apt-get update
          apt-get install -y ${PKG}
          echo "-----> installed packages: ${PKG}"
      else
        echo "-----> no additional packages found!"      
      fi
      sleep 1
EOF
)

    id=$(docker run -d "$IMG" /bin/bash -e -c "$CMD")
    docker attach "$id"
    test "$(docker wait "$id")" -eq 0
    docker commit "$id" "$IMG" > /dev/null
  else
    echo "-----> apt-packages not found"
  fi
}

apt_get_install_main "$@"
